=== joaopinto461/Browser-Rolap/xml/metadataDW.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.w3schools.com"
    xmlns="http://www.w3schools.com"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    <xs:element name="metadata">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="database" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="multidimensionalmodel" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="db_connection" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="tables" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="db_connection">
        <xs:complexType>
            <xs:attribute name="adapter" type="xs:string" use="required"/>
            <xs:attribute name="host" type="xs:string" use="required"/>
            <xs:attribute name="username" type="xs:string" use="required"/>
            <xs:attribute name="password" type="xs:string" use="required"/>
            <xs:attribute name="path" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="tables">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="table" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="columns" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="primary_key" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="foreign_keys" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="columns">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="column" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="column">
        <xs:complexType>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="primary_key">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="key" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="key">
        <xs:complexType>
            <xs:attribute name="column_src" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="foreign_keys">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="key_ref" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="key_ref">
        <xs:complexType>
            <xs:attribute name="column_ref_src" type="xs:IDREF" use="required"/>
            <xs:attribute name="table_ref_src" type="xs:IDREF" use="required"/>
            <xs:attribute name="table_ref" type="xs:IDREF" use="required"/>
            <xs:attribute name="column_ref" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="multidimensionalmodel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cubes" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="dimensions" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cubes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cube" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cube">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fact_table" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cube_dimensions" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cube_measures" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="table_ref" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="fact_table">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fact" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="fact">
        <xs:complexType>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="display_name" type="xs:string" use="required"/>
            <xs:attribute name="column_ref" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cube_dimensions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cube_dimension" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cube_dimension">
        <xs:complexType>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="dimension_ref" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cube_measures">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="measure" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="measure">
        <xs:complexType>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="display_name" type="xs:string" use="required"/>
            <xs:attribute name="operation" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dimensions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dimension" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="dimension">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hierarchies" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="levels" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="display_name" type="xs:string" use="required"/>
            <xs:attribute name="base_level" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="hierarchies">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hierarchy" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="hierarchy">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hierarchy_level" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="display_name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="hierarchy_level">
        <xs:complexType>
            <xs:attribute name="level_ref" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="levels">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="level" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="level">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="property" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="group_by" type="xs:IDREF" use="required"/>
            <xs:attribute name="sort_by" type="xs:IDREF" use="required"/>
            <xs:attribute name="display_by" type="xs:IDREF" use="required"/>
            <xs:attribute name="table_ref" type="xs:IDREF" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="property">
        <xs:complexType>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="column_ref" type="xs:IDREF" use="required"/>
            <xs:attribute name="display_name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== joaopinto461/Browser-Rolap/xml/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata xmlns="MyDef" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="MyDef file:/Applications/oxygen/metadataDW.xsd">
 <database>
  <db_connection adapter="" host="localhost" username="" password="" path=""/>
  <tables>
   <table id="table_sales_fact_1997" name="sales_fact_1997">
    <columns>
     <column id="table_sales_fact_1997_column_product_id" name="product_id" type="integer"/>
     <column id="table_sales_fact_1997_column_time_id" name="time_id" type="integer"/>
     <column id="table_sales_fact_1997_column_customer_id" name="customer_id" type="integer"/>
     <column id="table_sales_fact_1997_column_promotion_id" name="promotion_id" type="integer"/>
     <column id="table_sales_fact_1997_column_store_id" name="store_id" type="integer"/>
     <column id="table_sales_fact_1997_column_store_sales" name="store_sales" type="double"/>
     <column id="table_sales_fact_1997_column_store_cost" name="store_cost" type="double"/>
     <column id="table_sales_fact_1997_column_unit_sales" name="unit_sales" type="double"/>
    </columns>
    <primary_key>
     <key column_src="table_sales_fact_1997_column_product_id"/>
     <key column_src="table_sales_fact_1997_column_time_id"/>
     <key column_src="table_sales_fact_1997_column_customer_id"/>
     <key column_src="table_sales_fact_1997_column_promotion_id"/>
     <key column_src="table_sales_fact_1997_column_store_id"/>
    </primary_key>
    <foreign_keys>
     <key_ref column_ref_src="table_sales_fact_1997_column_product_id" 
      table_ref_src="table_sales_fact_1997" table_ref="table_product" 
      column_ref="table_product_column_product_id"/>
     <key_ref column_ref_src="table_sales_fact_1997_column_time_id" 
      table_ref_src="table_sales_fact_1997" table_ref="table_time_by_day"
      column_ref="table_time_by_day_column_time_id"/>
     <key_ref column_ref_src="table_sales_fact_1997_column_customer_id" 
      table_ref_src="table_sales_fact_1997" table_ref="table_customer"
      column_ref="table_customer_column_customer_id"/>
     <key_ref column_ref_src="table_sales_fact_1997_column_promotion_id" 
      table_ref_src="table_sales_fact_1997" 
      table_ref="table_promotion" 
      column_ref="table_promotion_column_promotion_id"/>
     <key_ref column_ref_src="table_sales_fact_1997_column_store_id" 
      table_ref_src="table_sales_fact_1997" 
      table_ref="table_store" 
      column_ref="table_store_column_store_id"/>
    </foreign_keys>
   </table>
   <table id="table_product" name="product">
    <columns>
     <column id="table_product_column_product_id" name="product_id" type="integer"/>
     <column id="table_product_column_product_class_id" name="product_class_id" type="integer"/>
     <column id="table_product_column_brand_name" name="brand_name" type="string"/>
     <column id="table_product_column_product_name" name="product_name" type="integer"/>
    </columns>
    <primary_key>
     <key column_src="table_product_column_product_id"/>
    </primary_key>
    <foreign_keys>
     <key_ref column_ref_src="table_product_column_product_class_id" 
      table_ref_src="table_product" table_ref="table_product_class" 
      column_ref="table_product_class_id"/>
    </foreign_keys>
   </table>
   <table id="table_product_class" name="product_class">
    <columns>
     <column id="table_product_class_id" name="product_class_id" type="integer"/>
     <column id="table_product_subcategory" name="product_subcategory" type="string"/>
     <column id="table_product_category" name="product_category" type="string"/>
     <column id="table_product_department" name="product_department" type="string"/>
     <column id="table_product_family" name="product_family" type="string"/>
    </columns>
    <primary_key>
     <key column_src="table_product_class_id"/>
    </primary_key>
   </table>
   <table id="table_time_by_day" name="time_by_day">
    <columns>
     <column id="table_time_by_day_column_time_id" name="time_id" type="integer"/>
     <column id="table_time_by_day_column_the_date" name="the_date" type="datetime"/>
     <column id="table_time_by_day_column_the_day" name="the_day" type="string"/>
     <column id="table_time_by_day_column_the_month" name="the_month" type="string"/>
     <column id="table_time_by_day_column_the_year" name="the_year" type="integer"/>
     <column id="table_time_by_day_column_day_of_month" name="day_of_month" type="integer"/>
     <column id="table_time_by_day_column_week_of_year" name="week_of_year" type="integer"/>
     <column id="table_time_by_day_column_month_of_year" name="month_of_year" type="integer"/>
     <column id="table_time_by_day_column_quarter" name="quarter" type="string"/>
     <column id="table_time_by_day_column_fiscal_period" name="fiscal_period" type="string"/>
    </columns>
    <primary_key>
     <key column_src="table_time_by_day_column_time_id"/>
    </primary_key>
   </table>
   <table id="table_customer" name="customer">
    <columns>
     <column id="table_customer_column_customer_id" name="customer_id" type="integer"/>
     <column id="table_customer_column_city" name="city" type="string"/>
     <column id="table_customer_column_state_province" name="state_province" type="string"/>
     <column id="table_customer_column_postal_code" name="postal_code" type="string"/>
     <column id="table_customer_column_country" name="country" type="string"/>
     <column id="table_customer_column_customer_region_id" name="customer_region_id" type="integer"/>
     <column id="table_customer_column_marital_status" name="marital_status" type="string"/>
     <column id="table_customer_column_gender" name="gender" type="string"/>
     <column id="table_customer_column_occupation" name="occupation" type="string"/>
     <column id="table_customer_column_education" name="education" type="string"/>
     <column id="table_customer_column_fullname" name="fullname" type="string"/>
    </columns>
    <primary_key>
     <key column_src="table_customer_column_customer_id"/>
    </primary_key>
    <foreign_keys>
     <key_ref column_ref_src="table_customer_column_customer_region_id"
      table_ref_src="table_customer" table_ref="table_region" 
      column_ref="table_region_column_region_id"/>
    </foreign_keys>
   </table>
   <table id="table_region" name="region">
    <columns>
     <column id="table_region_column_region_id" name="region_id" type="integer"/>
     <column id="table_region_column_sales_city" name="sales_city" type="string"/>
     <column id="table_region_column_sales_state_province" name="sales_state_province" type="string"/>
     <column id="table_region_column_sales_district" name="sales_district" type="string"/>
     <column id="table_region_column_sales_region" name="sales_region" type="string"/>
     <column id="table_region_column_sales_country" name="sales_country" type="string"/>
    </columns>
    <primary_key>
     <key column_src="table_region_column_region_id"/>
    </primary_key>
   </table>
   <table id="table_promotion" name="promotion">
    <columns>
     <column id="table_promotion_column_promotion_id" name="promotion_id" type="integer"/>
     <column id="table_promotion_column_promotion_district_id" name="promotion_district_id" type="integer"/>
     <column id="table_promotion_column_promotion_name" name="promotion_name" type="string"/>
     <column id="table_promotion_column_media_type" name="media_type" type="string"/>
     <column id="table_promotion_column_cost" name="cost" type="double"/>
     <column id="table_promotion_column_start_date" name="start_date" type="datetime"/>
     <column id="table_promotion_column_end_date" name="end_date" type="datetime"/>
    </columns>
    <primary_key>
     <key column_src="table_promotion_column_promotion_id"/>
    </primary_key>
   </table>
   <table id="table_store" name="store">
    <columns>
     <column id="table_store_column_store_id" name="store_id" type="integer"/>
     <column id="table_store_column_store_type" name="store_type" type="string"/>
     <column id="table_store_column_region_id" name="region_id" type="integer"/>
     <column id="table_store_column_store_name" name="store_name" type="string"/>
     <column id="table_store_column_store_number" name="store_number" type="integer"/>
     <column id="table_store_column_store_city" name="store_city" type="string"/>
     <column id="table_store_column_store_state" name="store_state" type="string"/>
     <column id="table_store_column_store_postal_code" name="store_postal_code" type="string"/>
     <column id="table_store_column_store_country" name="store_country" type="string"/>
     <column id="table_store_column_store_manager" name="store_manager" type="string"/>
     <column id="table_store_column_store_sqft" name="store_sqft" type="integer"/>
    </columns>
    <primary_key>
     <key column_src="table_store_column_store_id"/>
    </primary_key>
    <foreign_keys>
     <key_ref column_ref_src="table_store_column_region_id" 
      table_ref_src="table_store" table_ref="table_region" 
      column_ref="table_region_column_region_id"/>
    </foreign_keys>
   </table>
  </tables>
 </database>
 <multidimensionalmodel>
  <cubes>
   <cube id="cube_sales_1997" name="Cube Sales 1997" table_ref="table_sales_fact_1997">
    <fact_table>
     <fact id="cube_sales_1997_fact_store_sales" display_name="Store Sales" 
      column_ref="table_sales_fact_1997_column_store_sales"/>
     <fact id="cube_sales_1997_fact_store_cost" display_name="Store Cost" 
      column_ref="table_sales_fact_1997_column_store_cost"/>
     <fact id="cube_sales_1997_fact_unit_sales" display_name="Store Unit Sales" 
      column_ref="table_sales_fact_1997_column_unit_sales"/>
    </fact_table>
    <cube_dimensions>
     <cube_dimension id="cube_dimension_time" dimension_ref="dimension_time"/>
    </cube_dimensions>
    <cube_measures>
